CREATE SEQUENCE NOTI_USER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE NOTI_GROUP_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE NOTI_USER  (
    NOTI_USER_ID NUMBER(10) PRIMARY KEY,
    NOTI_USER_NAME VARCHAR2(50) NOT NULL,
    NOTI_USER_TOKEN VARCHAR2(50),
    NOTI_USER_CHANNEL VARCHAR2(50),
    CONSTRAINT UK_USER_NAME UNIQUE (NOTI_USER_NAME)
);

CREATE TABLE NOTI_GROUP  (
    NOTI_GROUP_ID NUMBER(10) PRIMARY KEY,
    NOTI_GROUP_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT UK_GROUP_NAME UNIQUE(NOTI_GROUP_NAME)
);

CREATE TABLE NOTI_GROUP_USER_MAPPING (
    NOTI_GROUP_ID NUMBER(10),
    NOTI_USER_ID NUMBER(10),
    CONSTRAINT PK_MAPPING PRIMARY KEY(NOTI_GROUP_ID, NOTI_USER_ID),
    CONSTRAINT FK_GROUP_ID FOREIGN KEY(NOTI_GROUP_ID) REFERENCES NOTI_GROUP (NOTI_GROUP_ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY(NOTI_USER_ID) REFERENCES NOTI_USER (NOTI_USER_ID)
);

INSERT INTO NOTI_USER (NOTI_USER_ID, NOTI_USER_NAME, NOTI_USER_TOKEN, NOTI_USER_CHANNEL) VALUES (NOTI_USER_SEQ.NEXTVAL,'user1','TEST_TOKEN','#errornoti');
INSERT INTO NOTI_USER (NOTI_USER_ID, NOTI_USER_NAME, NOTI_USER_TOKEN, NOTI_USER_CHANNEL) VALUES (NOTI_USER_SEQ.NEXTVAL,'user2','TEST_TOKEN','#errornoti');
INSERT INTO NOTI_USER (NOTI_USER_ID, NOTI_USER_NAME, NOTI_USER_TOKEN, NOTI_USER_CHANNEL) VALUES (NOTI_USER_SEQ.NEXTVAL,'user3','TEST_TOKEN','#errornoti');

INSERT INTO NOTI_GROUP (NOTI_GROUP_ID, NOTI_GROUP_NAME) VALUES (NOTI_GROUP_SEQ.NEXTVAL,'group1');
INSERT INTO NOTI_GROUP (NOTI_GROUP_ID, NOTI_GROUP_NAME) VALUES (NOTI_GROUP_SEQ.NEXTVAL,'group2');
INSERT INTO NOTI_GROUP (NOTI_GROUP_ID, NOTI_GROUP_NAME) VALUES (NOTI_GROUP_SEQ.NEXTVAL,'group3');

INSERT INTO NOTI_GROUP_USER_MAPPING (NOTI_GROUP_ID, NOTI_USER_ID) VALUES (1,1);
INSERT INTO NOTI_GROUP_USER_MAPPING (NOTI_GROUP_ID, NOTI_USER_ID) VALUES (1,2);
INSERT INTO NOTI_GROUP_USER_MAPPING (NOTI_GROUP_ID, NOTI_USER_ID) VALUES (1,3);
INSERT INTO NOTI_GROUP_USER_MAPPING (NOTI_GROUP_ID, NOTI_USER_ID) VALUES (2,1);
INSERT INTO NOTI_GROUP_USER_MAPPING (NOTI_GROUP_ID, NOTI_USER_ID) VALUES (2,2);
INSERT INTO NOTI_GROUP_USER_MAPPING (NOTI_GROUP_ID, NOTI_USER_ID) VALUES (3,1);

COMMIT;